INSERT INTO CUSTOMER (ID, NAME, PHONE, EMAIL) VALUES (1, 'Nguyen Van A', '0909000111', 'a@example.com');
INSERT INTO EMPLOYEE (ID, NAME, ROLE) VALUES (1, 'Tran Van B', 'Admin');
INSERT INTO COUPON (ID, CODE, PERCENT) VALUES (1, 'WELCOME10', 10);
INSERT INTO DISCOUNT_CAMPAIGN (ID, NAME, START_DATE, END_DATE) VALUES (1, 'Tet Sale', '2025-01-01', '2025-01-10');
INSERT INTO ATTRIBUTE (ID, NAME, VALUE) VALUES (1, 'Color', 'Red');
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION) VALUES (1, 'Phone X', 'Flagship phone');
INSERT INTO PRODUCT_VARIANT (ID, SKU, PRICE, PRODUCT_ID) VALUES (1, 'PX-001', 999.99, 1);
INSERT INTO variant_attribute (variant_id, attribute_id) VALUES (1,1);
